import Vue from 'vue';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
Vue.component('fa-icon', FontAwesomeIcon);

// Using
import {
  faTachometerAlt,
  faAngleRight,
  faEnvelope,
  faBell,
  faBullhorn,
  faSignOutAlt,
  faBars,
  faTimes,
  faAngleDoubleRight,
  faMapMarkerAlt,
  faUserSecret,
  faHeadset,
  faPaintBrush,
  faCogs,
  faAsterisk,
  faMap,
  faUserFriends,
  faCaretRight,
  faUserTag,
  faShoppingCart,
  faArrowUp,
  faPlus,
  faHeart,
  faServer,
  faSearch,
  faEdit,
  faInfoCircle,
  faTrashAlt,
  faChevronRight,
  faChevronLeft,
  faQuestionCircle,
  faSave,
  faLock,
  faEyeSlash,
  faEye,
  faTrash
} from '@fortawesome/free-solid-svg-icons';

// Handle
library.add(
  faTachometerAlt,
  faAngleRight,
  faEnvelope,
  faBell,
  faBullhorn,
  faSignOutAlt,
  faBars,
  faTimes,
  faAngleDoubleRight,
  faMapMarkerAlt,
  faUserSecret,
  faHeadset,
  faPaintBrush,
  faCogs,
  faAsterisk,
  faMap,
  faUserFriends,
  faCaretRight,
  faUserTag,
  faShoppingCart,
  faArrowUp,
  faPlus,
  faHeart,
  faServer,
  faSearch,
  faEdit,
  faInfoCircle,
  faTrashAlt,
  faChevronRight,
  faChevronLeft,
  faQuestionCircle,
  faSave,
  faLock,
  faEyeSlash,
  faEye,
  faTrash
);