<template>
  <section class="ChatDashboard">
    <section class="scroll-container">
      <div class="MyChatContent">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore at quae totam harum, voluptate autem neque dolore esse fugiat odit, accusantium aperiam, voluptatibus iste! Porro hic esse unde ipsam modi veritatis dolorum blanditiis architecto. Magni dolor placeat dignissimos repellendus delectus soluta quia nesciunt rerum ad voluptatibus saepe illum quas, velit a exercitationem natus inventore harum repudiandae. Fugiat fuga obcaecati qui aut et autem porro architecto itaque, molestias voluptatem voluptatum ipsa expedita mollitia praesentium debitis repudiandae veritatis atque harum quisquam impedit veniam sunt, quod voluptatibus? Asperiores numquam temporibus, blanditiis deserunt iure, facere eos suscipit, quidem mollitia amet unde nostrum nemo! Quam nemo fugiat alias saepe inventore quis distinctio dignissimos magni voluptates illo, odit itaque accusamus doloribus ipsam, commodi sed iste et voluptate recusandae exercitationem mollitia. Rem enim, molestiae sed nulla atque tempora velit sequi. Tempore dolorum recusandae, cupiditate ad pariatur incidunt sed labore animi unde omnis temporibus nulla eos id ipsum perferendis, maxime quam aliquam possimus? Officia corrupti sunt ducimus doloremque fugiat dolorem cum aliquid, et quidem maxime maiores quo debitis consequatur sed nobis eaque aliquam laboriosam! Quis consequuntur minima at et distinctio voluptates ea? Hic, esse maxime nam fugiat tempore distinctio repudiandae minus quisquam laboriosam, ipsa repellendus ut quidem assumenda.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore at quae totam harum, voluptate autem neque dolore esse fugiat odit, accusantium aperiam, voluptatibus iste! Porro hic esse unde ipsam modi veritatis dolorum blanditiis architecto. Magni dolor placeat dignissimos repellendus delectus soluta quia nesciunt rerum ad voluptatibus saepe illum quas, velit a exercitationem natus inventore harum repudiandae. Fugiat fuga obcaecati qui aut et autem porro architecto itaque, molestias voluptatem voluptatum ipsa expedita mollitia praesentium debitis repudiandae veritatis atque harum quisquam impedit veniam sunt, quod voluptatibus? Asperiores numquam temporibus, blanditiis deserunt iure, facere eos suscipit, quidem mollitia amet unde nostrum nemo! Quam nemo fugiat alias saepe inventore quis distinctio dignissimos magni voluptates illo, odit itaque accusamus doloribus ipsam, commodi sed iste et voluptate recusandae exercitationem mollitia. Rem enim, molestiae sed nulla atque tempora velit sequi. Tempore dolorum recusandae, cupiditate ad pariatur incidunt sed labore animi unde omnis temporibus nulla eos id ipsum perferendis, maxime quam aliquam possimus? Officia corrupti sunt ducimus doloremque fugiat dolorem cum aliquid, et quidem maxime maiores quo debitis consequatur sed nobis eaque aliquam laboriosam! Quis consequuntur minima at et distinctio voluptates ea? Hic, esse maxime nam fugiat tempore distinctio repudiandae minus quisquam laboriosam, ipsa repellendus ut quidem assumenda.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore at quae totam harum, voluptate autem neque dolore esse fugiat odit, accusantium aperiam, voluptatibus iste! Porro hic esse unde ipsam modi veritatis dolorum blanditiis architecto. Magni dolor placeat dignissimos repellendus delectus soluta quia nesciunt rerum ad voluptatibus saepe illum quas, velit a exercitationem natus inventore harum repudiandae. Fugiat fuga obcaecati qui aut et autem porro architecto itaque, molestias voluptatem voluptatum ipsa expedita mollitia praesentium debitis repudiandae veritatis atque harum quisquam impedit veniam sunt, quod voluptatibus? Asperiores numquam temporibus, blanditiis deserunt iure, facere eos suscipit, quidem mollitia amet unde nostrum nemo! Quam nemo fugiat alias saepe inventore quis distinctio dignissimos magni voluptates illo, odit itaque accusamus doloribus ipsam, commodi sed iste et voluptate recusandae exercitationem mollitia. Rem enim, molestiae sed nulla atque tempora velit sequi. Tempore dolorum recusandae, cupiditate ad pariatur incidunt sed labore animi unde omnis temporibus nulla eos id ipsum perferendis, maxime quam aliquam possimus? Officia corrupti sunt ducimus doloremque fugiat dolorem cum aliquid, et quidem maxime maiores quo debitis consequatur sed nobis eaque aliquam laboriosam! Quis consequuntur minima at et distinctio voluptates ea? Hic, esse maxime nam fugiat tempore distinctio repudiandae minus quisquam laboriosam, ipsa repellendus ut quidem assumenda.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore at quae totam harum, voluptate autem neque dolore esse fugiat odit, accusantium aperiam, voluptatibus iste! Porro hic esse unde ipsam modi veritatis dolorum blanditiis architecto. Magni dolor placeat dignissimos repellendus delectus soluta quia nesciunt rerum ad voluptatibus saepe illum quas, velit a exercitationem natus inventore harum repudiandae. Fugiat fuga obcaecati qui aut et autem porro architecto itaque, molestias voluptatem voluptatum ipsa expedita mollitia praesentium debitis repudiandae veritatis atque harum quisquam impedit veniam sunt, quod voluptatibus? Asperiores numquam temporibus, blanditiis deserunt iure, facere eos suscipit, quidem mollitia amet unde nostrum nemo! Quam nemo fugiat alias saepe inventore quis distinctio dignissimos magni voluptates illo, odit itaque accusamus doloribus ipsam, commodi sed iste et voluptate recusandae exercitationem mollitia. Rem enim, molestiae sed nulla atque tempora velit sequi. Tempore dolorum recusandae, cupiditate ad pariatur incidunt sed labore animi unde omnis temporibus nulla eos id ipsum perferendis, maxime quam aliquam possimus? Officia corrupti sunt ducimus doloremque fugiat dolorem cum aliquid, et quidem maxime maiores quo debitis consequatur sed nobis eaque aliquam laboriosam! Quis consequuntur minima at et distinctio voluptates ea? Hic, esse maxime nam fugiat tempore distinctio repudiandae minus quisquam laboriosam, ipsa repellendus ut quidem assumenda.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore at quae totam harum, voluptate autem neque dolore esse fugiat odit, accusantium aperiam, voluptatibus iste! Porro hic esse unde ipsam modi veritatis dolorum blanditiis architecto. Magni dolor placeat dignissimos repellendus delectus soluta quia nesciunt rerum ad voluptatibus saepe illum quas, velit a exercitationem natus inventore harum repudiandae. Fugiat fuga obcaecati qui aut et autem porro architecto itaque, molestias voluptatem voluptatum ipsa expedita mollitia praesentium debitis repudiandae veritatis atque harum quisquam impedit veniam sunt, quod voluptatibus? Asperiores numquam temporibus, blanditiis deserunt iure, facere eos suscipit, quidem mollitia amet unde nostrum nemo! Quam nemo fugiat alias saepe inventore quis distinctio dignissimos magni voluptates illo, odit itaque accusamus doloribus ipsam, commodi sed iste et voluptate recusandae exercitationem mollitia. Rem enim, molestiae sed nulla atque tempora velit sequi. Tempore dolorum recusandae, cupiditate ad pariatur incidunt sed labore animi unde omnis temporibus nulla eos id ipsum perferendis, maxime quam aliquam possimus? Officia corrupti sunt ducimus doloremque fugiat dolorem cum aliquid, et quidem maxime maiores quo debitis consequatur sed nobis eaque aliquam laboriosam! Quis consequuntur minima at et distinctio voluptates ea? Hic, esse maxime nam fugiat tempore distinctio repudiandae minus quisquam laboriosam, ipsa repellendus ut quidem assumenda.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore at quae totam harum, voluptate autem neque dolore esse fugiat odit, accusantium aperiam, voluptatibus iste! Porro hic esse unde ipsam modi veritatis dolorum blanditiis architecto. Magni dolor placeat dignissimos repellendus delectus soluta quia nesciunt rerum ad voluptatibus saepe illum quas, velit a exercitationem natus inventore harum repudiandae. Fugiat fuga obcaecati qui aut et autem porro architecto itaque, molestias voluptatem voluptatum ipsa expedita mollitia praesentium debitis repudiandae veritatis atque harum quisquam impedit veniam sunt, quod voluptatibus? Asperiores numquam temporibus, blanditiis deserunt iure, facere eos suscipit, quidem mollitia amet unde nostrum nemo! Quam nemo fugiat alias saepe inventore quis distinctio dignissimos magni voluptates illo, odit itaque accusamus doloribus ipsam, commodi sed iste et voluptate recusandae exercitationem mollitia. Rem enim, molestiae sed nulla atque tempora velit sequi. Tempore dolorum recusandae, cupiditate ad pariatur incidunt sed labore animi unde omnis temporibus nulla eos id ipsum perferendis, maxime quam aliquam possimus? Officia corrupti sunt ducimus doloremque fugiat dolorem cum aliquid, et quidem maxime maiores quo debitis consequatur sed nobis eaque aliquam laboriosam! Quis consequuntur minima at et distinctio voluptates ea? Hic, esse maxime nam fugiat tempore distinctio repudiandae minus quisquam laboriosam, ipsa repellendus ut quidem assumenda.
      </div>
    </section>
  </section>
</template>

<script>
export default {

}
</script>